### ISSUE TITLE
Can someone help me see why my 'startGameTimer' is not working?

### ISSUE THREAD

**Issue by jshaw22** [scintillating-doughnut/scintillating-doughnut#49]
I declared a global variable, `timeInSeconds = 0`. 
In the Game State object, I set `this.gameTime = timeInSeconds`.
Also in the gamestate object I call `startGameTimer()`

startGameTimer() recursively calls itself every 1 second while incrementing timeInSeconds:

``` javascript
var startGameTimer = function () {
  timeInSeconds++;
  setTimeout(startGameTimer, 1000);
};
```

Yet in the live-test it's always 0. Why?!

**Comment by themisterkai** [comment]
Have you tried calling it outside of the gamestate object to see if it works that way?

**Comment by jshaw22** [comment]
Fixed.
